backend:
  name: auth0
  auth0_domain: "dev-akzfdebi17lb3u37.us.auth0.com"
  auth0_client_id: "DzAZ7ErgUQ0eSf18Y5is1QvNvwO7hJyE"
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["order"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number", default: 1 }
